name: Test Workflow

on:
  workflow_dispatch:

jobs:
  composite-test:
    name: Composite Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test the Local Action
        uses: ./ # Path to the "main" action.yml file
